server:
  port: 64417
  ssl:
    enabled: true
    key-store-type: pkcs12
    key-store: keystore.p12
    key-store-password: 9979
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${MEMBER_MARIA_URL}
    username: ${MEMBER_MARIA_USER}
    password: ${MEMBER_MARIA_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          default_batch_fetch_size: 500
  application:
    name: member-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://k9b204.p.ssafy.io:8761/eureka