server:
  port: 64419
  ssl:
    enabled: true
    key-store-type: pkcs12
    key-store: keystore.p12
    key-store-password: 9979

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${CALLING_MARIA_URL}
    username: ${CALLING_MARIA_USER}
    password: ${CALLING_MARIA_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          default_batch_fetch_size: 500
