spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${CALL_MARIA_URL}
    username: ${CALL_MARIA_USER}
    password: ${CALL_MARIA_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          default_batch_fetch_size: 500