server:
  port: 64415
  ssl:
    enabled: true
    key-store-type: pkcs12
    key-store: keystore.p12
    key-store-password: 9979
spring:
  application:
    name: report-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${REPORT_MARIA_URL}
    username: ${MEMBER_MARIA_USER}
    password: ${MEMBER_MARIA_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          default_batch_fetch_size: 500
  kafka:
    bootstrap-servers: ${KAFKA_SERVER}
    consumer:
      group-id: report-consumer
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://k9b204.p.ssafy.io:8761/eureka
  instance:
    hostname: k9b204.p.ssafy.io
    secure-port: 64415
    secure-port-enabled: true
    non-secure-port-enabled: false
    secure-virtual-host-name: k9b204.p.ssafy.io
    home-page-url-path: https://k9b204.p.ssafy.io:64415/
    status-page-url-path: https://k9b204.p.ssafy.io:64415/
    health-check-url: https://k9b204.p.ssafy.io:64415/
passport:
  key: ${SECRETE_KEY}
  algorithm: HmacSHA256